[package]
name = "intcode"
version = "0.1.0"
authors = ["Frank de Jong <f.jin@protonmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
rayon = "1.2.1"
aoc = { path = "../../aoc/" }

[dev-dependencies]
test-log = { path = "../../test-log/" }
