[package]
name = "test-log"
version = "0.1.0"
authors = ["frank <frank.049@hotmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.23", features = ["full"] }
quote = "0.6.10"

[dev-dependencies]
env_logger = "0.6.0"
log = "0.4.6"
