[package]
name = "day25"
version = "0.1.0"
authors = ["frank <frank.049@hotmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.6"
env_logger = "0.6.0"
vpsearch = "1.3.5"
regex = "1.1.0"
lazy_static = "1.2.0"
petgraph = "0.4.13"

[dev-dependencies]
test-log = { path = "../../test-log/" }
